---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ww.baopintui.cn
  resources:
  - cronbydps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ww.baopintui.cn
  resources:
  - cronbydps/finalizers
  verbs:
  - update
- apiGroups:
  - ww.baopintui.cn
  resources:
  - cronbydps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "batch"
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update