apiVersion: ww.baopintui.cn/v1
kind: Cronbydp
metadata:
  name: cronbydp-sample
  namespace: cronbydp-system
spec:
  # TODO(user): Add fields here
  namespaces:
  - default
  - ks-prod
  annotationname: syncimage
